trigger: none

stages:
  - template: /eng/pipelines/templates/stages/archetype-sdk-tests.yml
    parameters:
      ServiceDirectory: containerregistry
      SupportedClouds: 'UsGov'
      Artifacts:
        - name: azure-containers-containerregistry
          groupId: com.azure
          safeName: azurecontainerscontainerregistry
      TimeoutInMinutes: 90
      EnvVars:
        AZURE_CLIENT_ID: $(CONTAINERREGISTRY_CLIENT_ID)
        AZURE_CLIENT_SECRET: $(CONTAINERREGISTRY_CLIENT_SECRET)
        AZURE_TENANT_ID: $(CONTAINERREGISTRY_TENANT_ID)
        AZURE_SUBSCRIPTION_ID: $(CONTAINERREGISTRY_SUBSCRIPTION_ID)